export const SIDE_NAVBAR = "SIDE_NAVBAR";
export const LOAD_SHOPPING_MALLS = "LOAD_SHOPPING_MALLS";
export const LOAD_SHOPS = "LOAD_SHOPS";
export const LOAD_FILTERED_SHOPS = "LOAD_FILTERED_SHOPS";
export const SHOP_FILTER = 'SHOP_FILTER'

//for you products
export const FOR_YOU_PRODUCTS = "FOR_YOU_PRODUCTS";
export const SINGLE_PRODUCT = "SINGLE_PRODUCT";
export const PRODUCT_DISPLAY_IMAGE = "PRODUCT_DISPLAY_IMAGE";

//search action types
export const SEARCH_INPUT = "SEARCH_INPUT";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";

// shops action types

export const SHOPHOMEPAGEUSER = 'SHOPHOMEPAGEUSER'
export const LOADPRODUCTS = 'LOADPRODUCTS'

// cart actions
export const LOAD_CART_PRODUCTS = 'LOAD_CART_PRODUCTS'

//auth action types

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_SIGNOUT = 'USER_SIGNOUT';