export const SIDE_NAVBAR = "SIDE_NAVBAR";
export const LOAD_SHOPPING_MALLS = "LOAD_SHOPPING_MALLS";
export const LOAD_SHOPS = "LOAD_SHOPS";
export const LOAD_PRODUCTS_FOR_YOU = "LOAD_PRODUCTS_FOR_YOU";