export const SIDE_NAVBAR = "SIDE_NAVBAR";
export const LOAD_SHOPPING_MALLS = "LOAD_SHOPPING_MALLS";
export const LOAD_SHOPS = "LOAD_SHOPS";
export const LOAD_FILTERED_SHOPS = "LOAD_FILTERED_SHOPS";
export const SHOP_FILTER = 'SHOP_FILTER'
export const FOR_YOU_PRODUCTS = "FOR_YOU_PRODUCTS";

// shop home page

export const SHOPHOMEPAGEUSER = 'SHOPHOMEPAGEUSER'
export const LOADPRODUCTS = 'LOADPRODUCTS'


//auth action types

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_SIGNOUT = 'USER_SIGNOUT';